#!/usr/bin/env bash

set -eu -o pipefail

# make sure dynupd is in $PATH - I thought the Dockerfile already did this though...
export PATH="/nsddyn/bin:$PATH"

NSD=$(command -v nsd)
DYNUPD=$(command -v dynupd)
NSDDYNUM=$(command -v nsddynum)

$NSD -4 -a 0.0.0.0 > nsd.log 2>&1 &
$DYNUPD -d -a 0.0.0.0:8080 -n example.com -z /etc/nsd/zones/example.com.zone > dynupd.log 2>&1 &

# print the IP addr assigned to the container so I know where to point clients
awk '/32 host/ { print f } {f=$2}' <<< "$(</proc/net/fib_trie)" | egrep -v "127." | sort | uniq

# keep alive until NSD or dynupd dies
while sleep 60; do
    ps aux | grep nsd | grep -q -v grep
    PID1STAT=$?
    ps aux | grep dynupd | grep -q -v grep
    PID2STAT=$?

    if [ $PID1STAT -ne 0 ] || [ $PID2STAT -ne 0 ]; then
        exit 2
    fi
done

# drop to a shell so we can attach and see what is going on
#exec $(command -v bash)

