#!/usr/bin/env bash

set -eu -o pipefail

if ! [ -f /nsddyn/nsdip ]; then
    echo "Failed to locate dynupd-broker IP address."
    exit 2
fi

DYNUPDIP=$(awk '/32 host/ { print f } {f=$2}' <<< "$(</proc/net/fib_trie)" | egrep -v "127." | sort | uniq)
echo $DYNUPDIP > /nsddyn/dynupdip

BROKERIP=$(</nsddyn/nsdip)
BROKERURI="http://${BROKERIP}:8081/api/dynupd-broker"

$NSDDYN_HOME/bin/dynupd -d -a 0.0.0.0:8080 -n example.com -z /nsd/example.com.zone -b $BROKERURI > dynupd.log 2>&1

