#!/usr/bin/env bash

set -eu -o pipefail

# log the ip addr so that external automation can pick it up.
# who needs Docker Compose?
IPADDR=$(awk '/32 host/ { print f } {f=$2}' <<< "$(</proc/net/fib_trie)" | egrep -v "127." | sort | uniq)
echo $IPADDR > /nsddyn/nsdip

nsd -4 -a 0.0.0.0 > nsd.log 2>&1 &
$NSDDYN_HOME/bin/dynupd-broker > dynupd-broker.log 2>&1 &

# keep alive until NSD or dynupd-broker exits
while sleep 60; do
    ps aux | grep nsd | grep -q -v grep
    PID1STAT=$?
    ps aux | grep dynupd-broker | grep -q -v grep
    PID2STAT=$?

    if [ $PID1STAT -ne 0 ] || [ $PID2STAT -ne 0 ]; then
        exit 2
    fi
done

