#!/usr/bin/env bash

set -e

STATUS=0
RESULTS="Exited early."

BLDDIR="$(dirname "$(dirname "$(dirname "$(realpath $0)")")")"
PODDIR="$BLDDIR"/podman/integrate
TESTLOG="run.log"
PODNAME="onebigpod"
IMGNAME="nsddyntesting"

VOLNAME="nsddyn_test_volume"
VOL="$HOME"/.local/share/containers/storage/volumes/"$VOLNAME"/_data

if ! [ -f "$BLDDIR"/cmd/dynupd/dynupd ]; then
    echo "Did you run the build first?"
    exit 1
fi

podman volume create "$VOLNAME"

function cleanup {
    cd "$PODDIR" || exit 1
    podman pod stop "$PODNAME" || echo "Failed to stop pod..."
    podman pod rm "$PODNAME" || echo "Failed to remove pod..."
    podman volume rm --force "$VOLNAME" || echo "Failed to cleanup the volume..."

    echo ""
    echo "$RESULTS"
    echo ""

    if [[ $STATUS -gt 0 ]]; then
        exit $STATUS
    fi
}

trap cleanup EXIT

cd "$VOL"

mkdir bin
cp "$BLDDIR"/cmd/dynupd/dynupd bin/
cp "$BLDDIR"/cmd/dynupd-broker/dynupd-broker bin/
cp "$BLDDIR"/cmd/nsddynum/nsddynum bin/
cp "$PODDIR"/automated_integration.sh bin/
cp "$PODDIR"/dynupd.Deploy bin/
cp "$PODDIR"/nsd.Deploy bin/
cp "$PODDIR"/runtest.Deploy bin/

mkdir etc
cp "$BLDDIR"/etc/dynupd-broker.json etc/
cp "$PODDIR"/example.com.zone etc/
cp "$PODDIR"/nsd.conf etc/
cp "$PODDIR"/nsddynccrc etc/
cp "$PODDIR"/nsddynpasswd etc/
chmod 0755 etc # need to let NSD read this dir for the zone file
sed -i 's/dyn\.//g' etc/dynupd-broker.json
sed -i 's/localhost/0\.0\.0\.0/g' etc/dynupd-broker.json

cd "$PODDIR"

podman image build -t "$IMGNAME" -f Containerfile .

podman pod create --name "$PODNAME" --volume "$VOLNAME":/nsddyn:z
podman create --pod "$PODNAME" --name dynupd --workdir /nsddyn "$IMGNAME" /nsddyn/bin/dynupd.Deploy
podman create --pod "$PODNAME" --name nsd --workdir /nsddyn "$IMGNAME" /nsddyn/bin/nsd.Deploy
podman create --pod "$PODNAME" --name runtest --workdir /nsddyn "$IMGNAME" /nsddyn/bin/runtest.Deploy
podman pod start "$PODNAME"



podman wait runtest

EXPECTED_VAL="All tests passed!"
RES=$(< "$VOL"/"$TESTLOG")
RESULTS="$RES"

if [[ $RES != $EXPECTED_VAL ]]; then
    STATUS=1
fi

