#!/usr/bin/env bash

# some weird bullshit with contexts means we need to copy suff from .. here
# before the Docker build will see them...
cp -f ../dynupd/*.py ./

docker build -t nsddyn_test:latest .
docker run -p 5000:5000 nsddyn_test:latest

# note to self...don't store any .py files here...
rm -f *.py
