#!/usr/bin/env bash

set -eu -o pipefail

PROGNAME="nsddyn installer"

PKGROOT="dirname $(readlink -f $0)"

function func_eprintf {
    printf "%s\n" "$1" 1>&2
}

PREFIX="${NSDDYN_PREFIX:-/opt/nsddyn}"

# TODO: make a PREFIX option to override /opt/nsddyn as the default prefix.
if [ -e "$PREFIX" ]; then
    func_eprintf "$PROGNAME: Warning: $PREFIX exists. Are you sure you want to overwrite an existing install? [Y/n] "
    read -r ANS

    if [ "$ANS" == "Y" ] || [ "$ANS" == "y" ] || [ -z "$ANS" ]; then
        func_eprintf "$PROGNAME: Info: will overwrite existing install. No attempt will be made to clean up orphaned files."
    else
        func_eprintf "$PROGNAME: Info: refusing to overwrite existing install. Exiting."
        exit 0
    fi
fi

mkdir -p $PREFIX/bin
mkdir -p $PREFIX/etc

# don't be silly and make nsddynum owned by the nsddyn user/group, otherwise a remote user could
# potentially exploit dynupd to execute nsddynum and modify the nsddynpasswd file...
install -g staff -o root -m 0750 $PKGROOT/bin/nsddynum $PREFIX/bin/
install -g nsddyn -o root -m 0750 $PKGROOT/bin/dynupd $PREFIX/bin/
install -g root -o root -m 0750 $PKGROOT/bin/dynupd-broker $PREFIX/bin/

install -g root -o root -m 0660 $PKGROOT/etc/nsddyn $PREFIX/etc/
install -g root -o root -m 0440 $PKGROOT/etc/dynupd.service $PREFIX/etc/
install -g root -o root -m 0440 $PKGROOT/etc/dynupd-broker.service $PREFIX/etc/
install -g root -o root -m 0440 $PKGROOT/etc/dynupd-broker.json $PREFIX/etc/

if [ -f /usr/local/bin/nsddynum ]; then
    func_eprintf "$PROGNAME: Warning: overwriting /usr/local/bin/nsddynum"
fi
ln -sf $PREFIX/bin/nsddynum /usr/local/sbin/nsddynum

if [ -f /etc/systemd/system/dynupd.service ]; then
    func_eprintf "$PROGNAME: Warning: overwriting /etc/systemd/system/dynupd.service"
fi
ln -sf $PREFIX/etc/dynupd.service /etc/systemd/system/dynupd.service

if [ -f /etc/systemd/system/dynupd-broker.service ]; then
    func_eprintf "$PROGNAME: Warning: overwriting /etc/systemd/system/dynupd-broker.service"
fi
ln -sf $PREFIX/etc/dynupd-broker.service /etc/systemd/system/dynupd-broker.service

if ! [ -f $PREFIX/etc/nsddynpasswd ]; then
    touch $PREFIX/etc/nsddynpasswd
    chmod 0640 $PREFIX/etc/nsddynpasswd
    chown root:nsddyn $PREFIX/etc/nsddynpasswd
fi

func_eprintf "$PROGNAME: Info: installation complete, sysadmin must manually enable dynupd service unit."
