#!/usr/bin/env bash

set -eu -o pipefail

PROGNAME="nsddyn installer"

PKGROOT="$(dirname $(readlink -f $0))"

FORCE='false'
PREFIX='/opt/nsddyn'

function func_eprintf {
    printf "%s\n" "$1" 1>&2
}

function func_usage {
    printf "%s\n" "Usage: install [-f] [-p PREFIX]"
    printf "%s\n" "   or: install -h"
    printf "%s\n" "Install nsddyn."
    printf "\n"
    printf "%s\t\t%s\n" "-h, --help" "Display this usage message."
    printf "%s\t\t%s\n" "-p, --prefix" "Specify the installation prefix, if unspecified, defaults to /opt/nsddyn."
    printf "%s\t\t%s\n" "-f, --force" "Overwrite, without prompting, any existing installation."
    printf "\n"
}

while [ $# -gt 0 ]; do
    case "$1" in
        -h | --help)
            func_usage
            exit 0
            ;;
        -p | --prefix)
            PREFIX="$2"
            shift 2
            ;;
        -f | --force)
            FORCE='true'
            shift 1
            ;;
        *)
            func_usage
            func_eprintf "$PROGNAME: error: unrecognized argument [$1]"
            func_eprintf "exiting..."
            exit 1
            ;;
    esac
done

if [ -e "$PREFIX" ] && [ "$FORCE" == "false" ]; then
    func_eprintf "$PROGNAME: Warning: $PREFIX exists. Are you sure you want to overwrite an existing install? [Y/n] "
    read -r ANS

    if [ "$ANS" == "Y" ] || [ "$ANS" == "y" ] || [ -z "$ANS" ]; then
        func_eprintf "$PROGNAME: Info: will overwrite existing install. No attempt will be made to clean up orphaned files."
    else
        func_eprintf "$PROGNAME: Info: refusing to overwrite existing install. Exiting."
        exit 0
    fi
fi

mkdir -p $PREFIX/bin
mkdir -p $PREFIX/etc

# don't be silly and make nsddynum owned by the nsddyn user/group, otherwise a remote user could
# potentially exploit dynupd to execute nsddynum and modify the nsddynpasswd file...
install -g staff -o root -m 0750 $PKGROOT/bin/nsddynum $PREFIX/bin/
install -g nsddyn -o root -m 0750 $PKGROOT/bin/dynupd $PREFIX/bin/
install -g root -o root -m 0750 $PKGROOT/bin/dynupd-broker $PREFIX/bin/

if [ -e "$PREFIX" ]; then

    if [ "$FORCE" == "false" ]; then
        func_eprintf "$PROGNAME: warning: nsddyn configuration exists. Do you want to overwrite it? [y/N] "
        read -r ANS
    fi

    if [ "$FORCE" == "true" ] || [ "$ANS" == "Y" ] || [ "$ANS" == "y" ]; then
        install -g root -o root -m 0660 $PKGROOT/etc/nsddyn $PREFIX/etc/
        install -g root -o root -m 0440 $PKGROOT/etc/dynupd.service $PREFIX/etc/
        install -g root -o root -m 0440 $PKGROOT/etc/dynupd-broker.service $PREFIX/etc/
        install -g root -o root -m 0440 $PKGROOT/etc/dynupd-broker.json $PREFIX/etc/
    else
        func_eprintf "$PROGNAME: info: leaving existing configuration in place."
    fi
fi

if [ -f /usr/local/bin/nsddynum ]; then
    func_eprintf "$PROGNAME: Warning: overwriting /usr/local/bin/nsddynum"
fi
ln -sf $PREFIX/bin/nsddynum /usr/local/sbin/nsddynum

if [ -f /etc/systemd/system/dynupd.service ]; then
    func_eprintf "$PROGNAME: Warning: overwriting /etc/systemd/system/dynupd.service"
fi
ln -sf $PREFIX/etc/dynupd.service /etc/systemd/system/dynupd.service

if [ -f /etc/systemd/system/dynupd-broker.service ]; then
    func_eprintf "$PROGNAME: Warning: overwriting /etc/systemd/system/dynupd-broker.service"
fi
ln -sf $PREFIX/etc/dynupd-broker.service /etc/systemd/system/dynupd-broker.service

if ! [ -f $PREFIX/etc/nsddynpasswd ]; then
    touch $PREFIX/etc/nsddynpasswd
    chmod 0640 $PREFIX/etc/nsddynpasswd
    chown root:nsddyn $PREFIX/etc/nsddynpasswd
fi

func_eprintf "$PROGNAME: Info: installation complete, sysadmin must manually enable dynupd service unit."
