#!/usr/bin/env bash

set -e

SUBVER="${DEBABI:-1}"

WRKDIR="$(mktemp -d)"
CURDIR="$(pwd)"
# Per Debian maintainer's guide, we want to avoid `-` in the upstream version number.
# Since I note development builds similarly to "1.1.0-dev3", I need to transform that
# to "1.1.0~dev3" to maintain compatabiliy with dpkg. A `-` is used to seporate the
# upstream version from the package/ABI version incremented by Debian.
PKGVER="$(cat VERSION | tr '-' '~')-$SUBVER"
PKGDIR="nsddyn_${PKGVER}_amd64"

function cleanup {
    rm -rf "$WRKDIR"

    if [ "$(whoami)" != "root" ]; then
        echo "Did you remember to build with \`fakeroot\` you silly goose?"
        echo "If not, you better know what you are doing."
        exit 1
    fi
}
trap cleanup EXIT

if [ "$SUBVER" == "" ]; then
    echo "You need to specify a Debian package version as an argument: i.e. 5"
    exit 1
fi

cd "$WRKDIR"
mkdir -p "$PKGDIR"/opt/catloaf/sbin
mkdir -p "$PKGDIR"/opt/catloaf/share/nsddyn
mkdir -p "$PKGDIR"/opt/catloaf/etc

BINDST="$PKGDIR"/opt/catloaf/sbin

cp "$CURDIR"/cmd/dynupd/dynupd "$BINDST"/
cp "$CURDIR"/cmd/dynupd-broker/dynupd-broker "$BINDST"/
cp "$CURDIR"/cmd/nsddynum/nsddynum "$BINDST"/

chmod 0550 "$BINDST"/dynupd
chmod 0550 "$BINDST"/dynupd-broker
chmod 0550 "$BINDST"/nsddynum

CONFDST="$PKGDIR"/opt/catloaf/share/nsddyn
cp "$CURDIR"/etc/dynupd-broker.json "$CONFDST"/
cp "$CURDIR"/etc/dynupd-broker.service "$CONFDST"/
cp "$CURDIR"/etc/dynupd.service "$CONFDST"/
cp "$CURDIR"/etc/nsddyn "$CONFDST"/

mkdir -p "$PKGDIR"/DEBIAN

CONTROL="\
Package: nsddyn
Version: $PKGVER
Architecture: amd64
Depends: nsd (>= 4.3.5), libc6 (>= 2.31)
Maintainer: Alex Necheff <pkg@necheff.net>
Homepage: https://www.necheff.net
Description: nsddyn provides a secure method for achieving Dynamic DNS when using NSD as an authoritative DNS server.
"

echo "$CONTROL" > "$PKGDIR"/DEBIAN/control

POSTINST="\
#!/usr/bin/env bash

set -e

adduser --system --group nsddyn || echo \"Nsddyn user already exists, proceeding anyways.\"

chown root:nsddyn /opt/catloaf/sbin/dynupd

if ! [ -f /opt/catloaf/etc/nsddynpasswd ]; then
    touch /opt/catloaf/etc/nsddynpasswd
    chmod 0640 /opt/catloaf/etc/nsddynpasswd
    chown root:nsddyn /opt/catloaf/etc/nsddynpasswd
fi
"

echo "$POSTINST" > "$PKGDIR"/DEBIAN/postinst
chmod 0555 "$PKGDIR"/DEBIAN/postinst

dpkg-deb --build "$PKGDIR"
cp "$PKGDIR".deb "$CURDIR"/

