server:
    do-ip4: yes
    port: 53
    username: nsd
    zonesdir: /nsddyn/etc/

remote-control:
    control-enable: yes
    control-interface: 127.0.0.1
    control-port: 8952
    server-key-file: "/etc/nsd/nsd_server.key"
    server-cert-file: "/etc/nsd/nsd_server.pem"
    control-key-file: "/etc/nsd/nsd_control.key"
    control-cert-file: "/etc/nsd/nsd_control.pem"

key:
    name: "thexfrkey."
    algorithm: hmac-sha512
    secret: "passwordpasswordpassword"

pattern:
    name: "thepattern"
    # since we are in a Podman pod and share a network namespace...everyone has the same IP.
    allow-notify: 127.0.0.1 thexfrkey.
    request-xfr: 127.0.0.1@5353 thexfrkey.

zone:
    name: "example.com"
    zonefile: "example.com.zone"
    include-pattern: "thepattern"

