LogLevel = "debug"

[[Secondaries]]
Name = "127.0.0.1:53"

[[Keys]]
Name = "thexfrkey."
Algo = "hmac-sha512"
Secret = "passwordpasswordpassword"

[[Zones]]
Name = "example.com"
Key = "thexfrkey."
File = "/nsddyn/etc/example.com.zone"
